name: Basic Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check Templates
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          
          # Just check if templates are modified
          for template in "TEMPLATE-ROUND1.md" "TEMPLATE-ROUND2.md" "TEMPLATE-ROUND3.md"; do
            if echo "$CHANGED" | grep -q "^$template"; then
              echo "::error::Modified template file: $template"
              exit 1
            fi
          done
          
          echo "::notice::No template modifications found"